client_id: '****'
client_secret: '****'

alpha_num:
    - 'A'
    - 'B'
    - 'C'
    - 'D'
    - 'E'
    - 'F'
    - 'G'
    - 'H'
    - 'I'
    - 'J'
    - 'K'
    - 'L'
    - 'M'
    - 'N'
    - 'O'
    - 'P'
    - 'Q'
    - 'R'
    - 'S'
    - 'T'
    - 'U'
    - 'V'
    - 'W'
    - 'X'
    - 'Y'
    - 'Z'
    - '#'
    - '~'

metal_genres:
    - 'black-metal'
    - 'bluegrass'
    - 'blues'
    - 'classical'
    - 'death-metal'
    - 'hard-rock'
    - 'hardcore'
    - 'heavy-metal'
    - 'metal'
    - 'metal-misc'
    - 'metalcore'
    - 'psych-rock'
    - 'punk'
    - 'punk-rock'
    - 'rock'
    - 'rock-n-roll'
    - 'rockabilly'
    # other valid genres
    - 'death'
    - 'grind'
    - 'doom'
    - 'thrash'